sonar.projectKey=Anthony_Romero_t8
sonar.projectName=Anthony_Romero_t8
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,.venv/**
sonar.host.url=https://sonarqube.ingsoftware.lat/
sonar.token=sqa_4e296de25b56b315988b9a9dfd137d2b4f97e7c3
sonar.tests=.
sonar.test.inclusions=**/tests/**,**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3